### ISSUE TITLE
'ErrorException' with message 'Array to string conversion' when set trusted proxies

### ISSUE THREAD

**Issue by ariews** [yaroslawww/laravel-force-https#1]
Hi @yaroslawww thanks for this great package! It helped me.

I get this error when I try to set trusted proxies. Following your [sample](https://github.com/yaroslawww/laravel-force-https#laravel-force-https-amazon-support)

```
    'set_trusted_proxies' => [
        'use_self_client_ip' => true,
        'ips' => [ /* array of trusted proxy ips from https://www.cloudflare.com/ips-v4 */ ],
    ],
```

I'm using PHP 7.1, Laravel 5.4, Debian 8 and CloudFlare.

**Comment by yaroslawww** [comment]
Thank you for pointing out the problem. Resolved in the new version (1.0.11)  https://packagist.org/packages/yaroslawww/laravel-force-https#1.0.11 . Please update or reinstall the package using сomposer
