### ISSUE TITLE
Redirect back to http

### ISSUE THREAD

**Issue by kikz4life** [yaroslawww/laravel-force-https#3]
Hi,

I just wanted to ask if this also handle the http redirect. What I was looking for was I only want one page in my app to be in HTTPS and the rest are HTTP. I'll be using HTTPS on the billing page only. So if the user current page is on HTTPS and when he access other pages he will be using the HTTP now. Can your plugin handle this?

**Comment by SaphiLC** [comment]
Why would you want to do that? https is a must fore everything these days

**Comment by shanitiwari01** [comment]
use Laravel Helpers

secure URL

https://medium.com/@tiwarishani/how-to-force-laravel-to-use-https-in-url-and-assets-7f99f5a18b00?sk=a7a61bde2fe7b2d8e1bb964a9b94838a
